---
title: "SA24204139 -11-10"
author: "sa24204139"
date: "2024-11-10"
output:
  html_document: default
  word_document: default
---
11.3
```{r}
compute_kth_term <- function(k, d, a) {
  norm_a <- sqrt(sum(a^2))
  term <- (-1)^k / (factorial(k) * 2^k) * 
          (norm_a^(2 * k + 2) / ((2 * k + 1) * (2 * k + 2))) * 
          (gamma((d + 1) / 2) * gamma(k + 3 / 2) / gamma(k + d / 2 + 1))
  
  return(term)
}
compute_sum <- function(n_terms, d, a) {
  sum_value <- 0
  for (k in 0:(n_terms - 1)) {
    sum_value <- sum_value + compute_kth_term(k, d, a)
  }
  return(sum_value)
}
a <- c(1, 2)
d <- 2
n_terms <- 100
result <- compute_sum(n_terms, d, a)
print(result)
```
11.5
```{r}
solve.equation <- function(k) {
  expr.integral <- function(u, n) {
    (1 + u^2 / (n - 1))^(-n / 2)
  }
  get.c <- function(n, a) {
    sqrt(a^2 * n / (n + 1 - a^2))
  }
  expr <- function(n, a) {
    this.integral <- function(u) expr.integral(u, n)
    c <- get.c(n - 1, a)
    2 / sqrt(pi * (n - 1)) * exp(lgamma(n / 2) - lgamma((n - 1) / 2)) * 
      integrate(this.integral, lower = 0, upper = c)$value
  }
  f <- function(a) {
    left <- expr(k, a)
    right <- expr(k + 1, a)
    left - right
  }
  eps <- 1e-2
  if ((f(eps) < 0 && f(sqrt(k) - eps) > 0) || (f(eps) > 0 && f(sqrt(k) - eps) < 0)) {
    r <- uniroot(f, interval = c(eps, sqrt(k) - eps))$root
  } else {
    r <- NA
  }

  return(r)
}
answer <- sapply(c(4:25, 100, 500, 1000), function(k) {
  solve.equation(k)
})
print(answer)
```
EXTRA
```{r}
Y <- c(0.54, 0.48, 0.33, 0.43, 1.00, 1.00, 0.91, 1.00, 0.21, 0.85)
tau <- 1  
lambda <- 1  
max_iter <- 1000
tol <- 1e-6
for (iter in 1:max_iter) {
  uncensored <- Y[Y < tau]
  censored <- Y[Y >= tau]
  E_Ti_censored <- tau + 1 / lambda  
  lambda_new <- length(Y) / (sum(uncensored) + length(censored) * E_Ti_censored)
  if (abs(lambda_new - lambda) < tol) {
    lambda <- lambda_new
    break
  }
  lambda <- lambda_new
}
cat("Estimated lambda using EM algorithm:", lambda, "\n")
lambda_mle <- length(Y) / sum(Y)
cat("MLE lambda ignoring censoring:", lambda_mle, "\n")
```