# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complete_design <- function(varlist, numbering = TRUE, size = 1L) {
    .Call(`_SA24204139_complete_design`, varlist, numbering, size)
}

rcpp_hello_world <- function() {
    .Call(`_SA24204139_rcpp_hello_world`)
}

